version: '3.3'
services:
  battleship-api:
    image: ag04/mb-battleship-api:0.2.0
    ports:
      - "8080:8080"
    environment:
      CONTEXT_PATH: "/battleship-api"
      SPRING_PROFILES_ACTIVE: "docker"
      LIQUIBASE_CONTEXTS: "dev"
